In [1]:
import pandas as pd

data = pd.read_csv("./../data/prepared_gasoline.csv")

In [6]:
data.sort_values(by=['date']).head()

,date,weekday,latitude,longitude,e5gas,dautobahn,autobahn,aral,esso,jet,shell,total,rotterdam,brent,wti,eurusd,vehicles
7454512,2014-05-16,5,51.480099,6.74439,1.519667,543.827148,0,0,0,0,0,0,0.622837,109.424042,101.258553,1.369886,25609.0
501265,2014-05-16,5,48.476601,9.22743,1.510875,23071.439453,0,0,0,0,0,0,0.622837,109.424042,101.258553,1.369886,40088.0
6419504,2014-05-16,5,51.970402,7.28063,1.585471,10605.699219,0,0,0,0,0,0,0.622837,109.424042,101.258553,1.369886,35834.0
1340714,2014-05-16,5,53.585701,7.22169,1.582684,21993.939453,0,0,0,0,0,0,0.622837,109.424042,101.258553,1.369886,15013.0
7078505,2014-05-16,5,49.144199,9.30840,1.573615,208.705856,0,0,0,0,0,0,0.622837,109.424042,101.258553,1.369886,42989.0

In [52]:
# reformat the data so that each row corresponds to one date, meaning all stations in one row on that date
# issues with this -- not all dates have observations for all stations -- and right now they are not in a standard order

In [53]:
data_group = data.set_index('date').groupby(level=0) \
    .apply(lambda data: data.reset_index(drop=True)) \
    .unstack().sort_index(axis=1, level=1)

data_group.columns = ['{}{}'.format(x[0], int(x[1]) + 1) for x in data_group.columns]

data_group

,weekday1,latitude1,longitude1,e5gas1,dautobahn1,autobahn1,aral1,esso1,jet1,shell1,...,aral14519,esso14519,jet14519,shell14519,total14519,rotterdam14519,brent14519,wti14519,eurusd14519,vehicles14519
date,,,,,,,,,,,,,,,,,,,,,
2014-05-16,5.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-17,6.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-18,0.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-19,1.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-20,2.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-21,3.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-22,4.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-23,5.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-24,6.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-25,0.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-26,1.0,48.121899,11.45140,1.51800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-27,2.0,48.121899,11.45140,1.52425,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-28,3.0,48.121899,11.45140,1.52800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-29,4.0,48.121899,11.45140,1.52800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-30,5.0,48.121899,11.45140,1.52800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-31,6.0,48.121899,11.45140,1.52800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-01,0.0,48.121899,11.45140,1.52800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-02,1.0,48.121899,11.45140,1.52800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-03,2.0,48.121899,11.45140,1.53425,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-04,3.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-05,4.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-06,5.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-07,6.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-08,0.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-09,1.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-10,2.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-11,3.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-12,4.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-13,5.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-06-14,6.0,48.121899,11.45140,1.53800,357.104431,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-11-12,4.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-13,5.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-14,6.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-15,0.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-16,1.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-17,2.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-18,3.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-19,4.0,51.169201,6.94895,1.31900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-20,5.0,51.169201,6.94895,1.30400,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-21,6.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-22,0.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-23,1.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-24,2.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-25,3.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-26,4.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-27,5.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-28,6.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-29,0.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-30,1.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-01,2.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-02,3.0,51.169201,6.94895,1.29900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-03,4.0,51.169201,6.94895,1.31525,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-04,5.0,51.169201,6.94895,1.30900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-05,6.0,51.169201,6.94895,1.30900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-06,0.0,51.169201,6.94895,1.30900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-07,1.0,51.169201,6.94895,1.28900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-08,2.0,51.169201,6.94895,1.26900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-09,3.0,51.169201,6.94895,1.26900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-10,4.0,51.169201,6.94895,1.26900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-11,5.0,51.169201,6.94895,1.26900,316.700775,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
data_group.shape

(575, 232304)

In [56]:
data_group.to_csv('./../data/grouped_gasoline.csv')

In [ ]:
import keras
from keras.models import Sequential  
from keras.layers.core import Dense, Activation  
from keras.layers.recurrent import LSTM

in_out_neurons = 232304  
hidden_neurons = 300

model = Sequential()
model.add(LSTM(hidden_neurons, return_sequences=False,
               input_shape=(None, in_out_neurons)))
model.add(Dense(in_out_neurons, input_dim=hidden_neurons))  
model.add(Activation("linear"))  
model.compile(loss="mean_squared_error", optimizer="rmsprop")

def _load_data(data, n_prev = 100):  
    """
    data should be pd.DataFrame()
    """

    docX, docY = [], []
    for i in range(len(data)-n_prev):
        docX.append(data.iloc[i:i+n_prev].as_matrix())
        docY.append(data.iloc[i+n_prev].as_matrix())
    alsX = np.array(docX)
    alsY = np.array(docY)

    return alsX, alsY

def train_test_split(df, test_size=0.1):  
    """
    This just splits data to training and testing parts
    """
    ntrn = round(len(df) * (1 - test_size))

    X_train, y_train = _load_data(df.iloc[0:ntrn])
    X_test, y_test = _load_data(df.iloc[ntrn:])

    return (X_train, y_train), (X_test, y_test)

(X_train, y_train), (X_test, y_test) = train_test_split(data)

/usr/local/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.